---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: file
  name: bg_image_webp
  label: bg_image_webp
- type: file
  name: bg_image
  label: bg_image
- type: file
  name: image_webp
  label: image_webp
- type: file
  name: image
  label: image
- type: text
  name: client
  label: client
- type: text
  name: category
  label: category
- type: text
  name: status
  label: status
