---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: file
  name: bg_image_webp
  label: bg_image_webp
- type: file
  name: bg_image
  label: bg_image
- type: file
  name: image_webp
  label: image_webp
- type: file
  name: image
  label: image
- type: text
  name: icon
  label: icon
